### ISSUE TITLE
The request timed out, cancell all the downloads

### ISSUE THREAD

**Issue by mamcx** [norsez/BDMultiDownloader#1]
I'm downloading from Azure a lot of images (2000). If I get this error:

NSLocalizedDescription=The request timed out., NSUnderlyingError=0x8626d90 "The request timed out."}

More than once, the downloads get stuck and keep waiting forever.

**Comment by norsez** [comment]
That's an error that throws out when no data is being downloaded from the sever within a specified time interval.   

I would make sure that your destination servers allow the number of concurrent connections and sizes of your downloads. Most servers protect themselves from flooding and bandwidth hog by ignoring connections from the originator which simply causes timeout errors for the ignored connections. 

## 

#end
