### ISSUE TITLE
Dlog Error - compile problem

### ISSUE THREAD

**Issue by sambudda** [norsez/BDMultiDownloader#7]
get this error on iOS 7.1 with Xcode 5.1.1

Undefined symbols for architecture i386:
  "_DLog", referenced from:
      -[BDMultiDownloader connection:didFailWithError:] in BDMultiDownloader.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by norsez** [comment]
I have replace DLog with NSLog now in this commit here https://github.com/norsez/BDMultiDownloader/commit/bb00707652015b05a7cee50dcb5580e0fecf0252
However, I haven't had time to update the podspec. Please update manually with the latest commit at this time.
